### ISSUE TITLE
Problem parsing pawn captures in san format

### ISSUE THREAD

**Issue by andrescavallin** [niklasf/chessops#12]
I am unable to make parseSan work 
I noticed that "xd5" will work bu "exd5" will throw an error. The problem is that when there is two pawns attacking one pawn I don't know to tell the parseSan function which column to use. Also I think that standard san is exd5 and should work without the need of removing any prefix.

This code will exemplify my point: (TypeScript)

```typescript
import { parseFen, INITIAL_BOARD_FEN } from 'chessops/fen';
import { Chess } from 'chessops/chess';
import { board } from 'chessops/debug';
import { parseSan } from 'chessops/san';

const locaBoard = parseFen(INITIAL_BOARD_FEN).unwrap();
const currentPostiion = Chess.fromSetup(locaBoard).unwrap();
var sanMove = parseSan(currentPostiion, "e4");


//LiveChess return thing like hxg4 to signal pawn on h column takes on g4
if (sanMove) currentPostiion.play(sanMove);
sanMove = parseSan(currentPostiion, "d5");
if (sanMove) currentPostiion.play(sanMove);
sanMove = parseSan(currentPostiion, "c4");
if (sanMove) currentPostiion.play(sanMove);
sanMove = parseSan(currentPostiion, "nf6");
if (sanMove) currentPostiion.play(sanMove);

//Everything goes fine
console.log(sanMove);
console.log(board(currentPostiion.board));

//But this will fail
sanMove = parseSan(currentPostiion, "exd5");
if (sanMove) currentPostiion.play(sanMove);
console.log(sanMove);
console.log(board(currentPostiion.board));

```

**Comment by niklasf** [comment]
Thanks for reporting. I'll add some more tests for SAN parsing and make a bugfix release shortly.

**Comment by andrescavallin** [comment]
I confirm the issue is solved, thanks very much for the quick response. I am using the library to integrate playing with DGT Electronic Boards on Lichess.org . Previously using chess.js and now I have migrated to chessops. Thanks!!!
