### ISSUE TITLE
SAN and/or UCI move list parsing

### ISSUE THREAD

**Issue by ddugovic** [niklasf/chessops#129]
I'm developing [Lichess Statbot](https://github.com/ddugovic/lishogi-discord/tree/lichess) to allow Discord users easy access to Lichess APIs.  I'm considering expanding use of one of its text-based commands:
`/eval [fen] [play]` using chessops-powered move validation (and maybe even SAN-to-UCI translation; fen optional; play optional)

Move validation and translation are challenging!

I guess users would prefer to simply type `/eval d4 Nf6` rather than typing or copying a FEN; but sometimes users might copy a FEN and provide additional moves e.g. `/eval rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2 Nf3 Nc6 f1d3 g8f6 O-O`.

Background:
Currently `/eval rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2` displays:
* GIF with last move using https://github.com/lichess-org/lila-gif
* Cloud evaluation and opening name "Sicilian Defense" using https://lichess.org/api#tag/Opening-Explorer
* Master games using https://lichess.org/api#tag/Opening-Explorer/operation/openingExplorerMaster
* History graph using QuickChart and https://lichess.org/api#tag/Opening-Explorer/operation/openingExplorerLichessHistory

**Comment by niklasf** [comment]
Cool! I can confirm that this library offers the required tools, that is, UCI, SAN, and FEN parsers with error handling, plus move making.

* https://niklasf.github.io/chessops/functions/util.parseUci.html
* https://niklasf.github.io/chessops/functions/san.parseSan.html
* https://niklasf.github.io/chessops/functions/fen.parseFen.html
