### ISSUE TITLE
Chess.hasInsufficientMaterial not entirely correct

### ISSUE THREAD

**Issue by schlawg** [niklasf/chessops#152]
I believe it should return true when a color has only the king & one bishop remaining. However, it returns false when both sides have a single bishop provided that the bishops occupy both square colors, even though neither side can mate.

**Comment by niklasf** [comment]
With opposite colored bishops help-mate is possible:

```
[FEN "7k/8/7K/2Bb4/8/8/8/8 b - - 0 1"]

1... Bg8 1. Bd4#
```

[(setup)](https://lichess.org/analysis/7k/8/7K/2Bb4/8/8/8/8_b_-_-_0_1?color=white)

**Comment by schlawg** [comment]
TIL!
