### ISSUE TITLE
Add cjs target

### ISSUE THREAD

**Issue by schlawg** [niklasf/chessops#166]
This issue is just to gauge your interest in accepting a PR that would do two things:

1. Create a cjs target in addition to esm
2. Move built javascripts to dist/cjs, dist/esm and remap imports in package.json.

And if you're not interested in 1 (I don't blame you), we could still do 2.

**Comment by niklasf** [comment]
Both sound good. When I set up the current layout `exports` in package.json wasn't widely supported, in particular not by rollup which lila was using. But things have changed.
