### ISSUE TITLE
 WARN  deprecated chessops@0.12.8: Version published from wrong branch

### ISSUE THREAD

**Issue by eguneys** [niklasf/chessops#176]
What is this warning, how do I get rid of it.

**Comment by niklasf** [comment]
Release 0.12.8 is marked as deprecated, because it was published by mistake.

For a quick fix, downgrade to 0.12.7.

Or upgrade to a newer version (latest is 0.14.0). See the [changelog for details](https://github.com/niklasf/chessops/blob/master/CHANGELOG.md).
