### ISSUE TITLE
can't use as part of script with import chessops/pgn etc. without type module

### ISSUE THREAD

**Issue by eguneys** [niklasf/chessops#181]
Could you please, add "type": "module" config into package.json otherwise I can't import this and use it as part of a script. It gives a bunch of errors.

**Comment by niklasf** [comment]
@schlawg any concerns wrt https://github.com/niklasf/chessops/pull/169?

**Comment by schlawg** [comment]
This should be fine and I think necessary for node imports as esm.

**Comment by schlawg** [comment]
did you want a PR, niklasf? His suggestion is sound and it's my mistake that line is not in there already.

**Comment by eguneys** [comment]
I don't appreciate you calling me as like

**Comment by niklasf** [comment]
Readded and releases as `v0.14.1`.
