### ISSUE TITLE
PGN parsing and writing

### ISSUE THREAD

**Issue by VincentCordobes** [niklasf/chessops#36]
Is it something that could be part of this library ?

Btw thank you for this awesome lib! :)

**Comment by niklasf** [comment]
Thanks.

Yes, absolutely, PGN handling is definitely within the scope of this library. To help make some decisions about data structures, can you please describe what kind of operations you would be doing with parsed games?

**Comment by VincentCordobes** [comment]
Currently, I'm building a tree that looks like:
```typescript
type Node = {
  ply: Ply
  fen: Fen
  san: San
  children: Node[]
}
```

Basically I would:
- Walk the tree like in the lichess analysis, including variations
- Search a set of games (repertoire) by position.

I've seen your work for [python](https://python-chess.readthedocs.io/en/latest/pgn.html) and this looks perfect.
Let me know if I can help ;)

**Comment by jtwires** [comment]
+1, a visitor interface like your `python-chess` would be fantastic

**Comment by niklasf** [comment]
I finished a basic [implementation](https://github.com/niklasf/chessops/blob/master/src/pgn.test.ts). Still needs more testing, documentation, and maybe some convenience methods/functions ...
