### ISSUE TITLE
Request for new release with ES Module Support

### ISSUE THREAD

**Issue by Mythral** [niklasf/chessops#37]
Hello,

Would it be possible to get a new release tagged with 6536614ede12cdaf0e894c31bda8645fe73abc1e in it? There's currently the same issue on the latest release of this package that was also on https://github.com/ornicar/chessground/issues/213 .

No rush here, just would be nice to have.

Happy Holidays!

**Comment by niklasf** [comment]
Hi, happy new year! Sorry, I marked this a read and then forgot. Published now, as v0.10.4.
