### ISSUE TITLE
Fen with empty castling field is accepted as valid

### ISSUE THREAD

**Issue by nortti** [niklasf/chessops#43]
E.g. <code>rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR&nbsp;w&nbsp;&nbsp;-&nbsp;0&nbsp;1</code>, with `w` and `-` separated by two spaces.

**Comment by niklasf** [comment]
Thanks for reporting. I think it's best to treat multiple spaces as one, especially for notation potentially entered by humans.
