### ISSUE TITLE
Fen with repeated tokens in castling field accepted as valid

### ISSUE THREAD

**Issue by nortti** [niklasf/chessops#44]
E.g. `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KKqq - 0 1`

Considering that a field like `qK` is rejected even though it could easily be accepted, I think it would be consistent to reject other technically invalid fields unless it's needed to accommodate variants.

**Comment by niklasf** [comment]
It's not needed for any of the supported variants, but my first instinct is to relax the parser nonetheless. Going with that, for now ...
