### ISSUE TITLE
Add board.ascii()?

### ISSUE THREAD

**Issue by fnogatz** [niklasf/chessops#6]
For debugging purposes in another project I implemented a method that returns a textual representation of a board:

```js
const board = this.#position.board
let color = 0
let s = '  +------------------------+\n'
for (let rank = 8; rank >= 1; rank--) {
  s += `${rank} |`
  for (let file of ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']) {
    const square = parseSquare(file+rank)
    const piece = board.get(square)
    let symbol = ' '
    if (piece) {
      symbol = '\x1B[30m' + pieceSymbol(piece.role, piece.color) + '\x1B[39m'
    }

    if (color) {
      s += `\x1B[42m ${symbol} \x1B[49m`
    } else {
      s += `\x1B[107m ${symbol} \x1B[49m`
    }

    color ^= 1 // switch color
  }

  s += '|\n'
  color ^= 1
}

s += '  +------------------------+\n'
s += '    a  b  c  d  e  f  g  h'
```

Result:

![Screenshot from 2020-07-27 09-57-10](https://user-images.githubusercontent.com/881988/88517741-9dcfdc00-cfef-11ea-8061-bc121858f6d4.png)

By changing `pieceSymbol`, this could also use the symbols known from FEN instead. In addition, the colorised output could be optional.

Would you be interested in integrating this directly into chessops? If so, you could simply adapt the code snippet, or I would do so and open a PR. Is there a better way to iterate over the `SquareSet.full()` in the order a8...h8...h1?

**Comment by niklasf** [comment]
To keep code size minimal, something like this exists in a separate module instead of as a method on `Board`: https://github.com/niklasf/chessops/blob/4cbdd3a6ade93a182f0278bf60eec07a5945b0bd/src/debug.ts#L24

Your version looks better, though. Pull requests welcome.

**Comment by niklasf** [comment]
Sorry, on second thought I prefer the terminal-independent ASCII version for debugging. A real console GUI might want a nicer view, but that doesn't have to be part of this lib.
