### ISSUE TITLE
Fifty-move and Threefold repetition rules

### ISSUE THREAD

**Issue by dandaneel** [niklasf/chessops#99]
Hello,
I would like to know if Fifty-move and Threefold repetition rules are planned or if there are out of this library's scope.
Thank you

**Comment by niklasf** [comment]
Good suggestions.

`pos.halfmove_clock` already exists, so would need a thin wrapper to provide variant specific rules.

Theefold requires a representation for the history of a game (not just the current position), which is out of scope for the library for now, but could be added in the future.

**Comment by dandaneel** [comment]
OK thank you for your response
